apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: infra-app-svc
spec:
  type: NodePort
  selector:
    app: infra-app
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5000